### ISSUE TITLE
Set up SSL

### ISSUE THREAD

**Issue by ryangallen** [monday-night-lights/mnl-api#15]
The [nginx config](https://github.com/monday-night-lights/mnl-api/blob/master/nginx/conf.d/mnl.conf) should be changed to run the app on port 443 with an SSL certificate.

We can generate test certs for development and use https://letsencrypt.org/ for production certificates.

**Comment by ryangallen** [comment]
@jdrager probably will need your help setting up real certs for integration/production

**Comment by ryangallen** [comment]
For int/prod environments: https://certbot.eff.org/#debianjessie-nginx

**Comment by jdrager** [comment]
Yeah, didn't mean to close that

**Comment by ryangallen** [comment]
My fault for putting "fixes #15" in the commit message

**Comment by ryangallen** [comment]
When we actually get this deployed, SSL will be required. In the meantime it works in development
